backend:
  name: github
  repo: youngheart12/gatsby-starter

media_library:
  name: cloudinary
  config:
    cloud_name: dilipcloudforcms
    api_key: 368434935873843


public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - {label: "Tags", name: "tags", widget: "list"}
      - { name: identifier, label: Identifier, widget : string, default: "blog"}
      - {name: 'thumbnail',label: "Featured Image", widget: "image"}

  - name: Jobs
    label: Jobs
    folder: jobs
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "job-post"}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - {name: 'thumbnail',label: "Featured Image", widget: "image"}
      - { name : title, label: Title}
      - {label: "Job Name",name: "Job", widget: "string"}
      - {label:  "Vaccancy", name: "Vaccancy ", widget: "number" }
      - { name: body, label: Body, widget: markdown }
      - {label: 'Job Location', name: 'Job Location', widget: 'string'}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: 'Job Type', name: 'Job Type',widget : 'select', options: ["Internship","Full Time"]}
      - { name: identifier, label: Identifier, widget : string, default: "jobs"}
